lib.name = float2bytearray2float
class.sources = float2bytearray.c bytearray2float.c

PDLIBBUILDER_DIR = /home/tek/repos/_clones/pure-data/pd-lib-builder
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder

# make install pdincludepath=~/repos/_clones/pure-data/pure-data/src/ objestsdir=./build
# info: installpath is '/usr/local/lib/pd-externals/float2bytearray2float'
